# Generated by Django 3.0.8 on 2020-10-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim_rating', '0007_sim_rate_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim_rate',
            name='user_id',
        ),
    ]
