# Generated by Django 3.0.8 on 2020-11-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_rating', '0009_sim_rate_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='link',
            new_name='uniqueid',
        ),
        migrations.AlterField(
            model_name='sim_rate',
            name='user_id',
            field=models.CharField(help_text='User ID', max_length=30, null=True),
        ),
    ]
