# Generated by Django 3.0.8 on 2020-11-21 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim_rating', '0010_auto_20201121_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='uniqueid',
            new_name='link',
        ),
    ]
