# Generated by Django 3.0.8 on 2020-12-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_rating', '0012_auto_20201202_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='source',
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ManyToManyField(null=True, to='sim_rating.Source'),
        ),
    ]
